import { EVVSubmission, StateConfig } from '@/types/evv';

export const mockStateConfigs: StateConfig[] = [
  {
    state: 'NJ',
    aggregator: 'HHAeXchange',
    roundingRuleMinutes: 15,
    gracePeriodMinutes: 7,
    altEvvStatus: 'Active',
    reasonCodes: [
      { code: '01', description: 'Caregiver forgot to clock in/out' },
      { code: '02', description: 'Patient emergency' },
      { code: '03', description: 'Device malfunction' },
      { code: '04', description: 'No internet/cell service' },
    ],
  },
  {
    state: 'TX',
    aggregator: 'HHAeXchange',
    roundingRuleMinutes: 15,
    gracePeriodMinutes: 0,
    altEvvStatus: 'Testing',
    reasonCodes: [
      { code: 'RC1', description: 'Mobile app failure' },
      { code: 'RC2', description: 'Fob unavailable' },
    ],
  },
  {
    state: 'FL',
    aggregator: 'Netsmart',
    roundingRuleMinutes: 1, // Exact minute billing usually for Tellus/Netsmart in FL
    gracePeriodMinutes: 5,
    altEvvStatus: 'Vendor Approved',
    reasonCodes: [
      { code: 'E1', description: 'Schedule changed at last minute' },
      { code: 'E2', description: 'Member refused service' },
    ],
  },
  {
    state: 'MN',
    aggregator: 'HHAeXchange',
    roundingRuleMinutes: 15,
    gracePeriodMinutes: 7,
    altEvvStatus: 'Not Started',
    reasonCodes: [
      { code: 'M1', description: 'Manual entry required' },
    ],
  },
];

export const mockEvvSubmissions: EVVSubmission[] = [
  {
    id: 'EVV-1001',
    visitId: 'VST-5432',
    patientName: 'Eleanor Vance',
    caregiverName: 'Sarah Jenkins',
    date: '2026-07-20',
    beginTime: '08:00 AM',
    endTime: '12:00 PM',
    serviceType: 'T1019 - Personal Care',
    location: '123 Main St, Newark, NJ',
    aggregator: 'HHAeXchange',
    state: 'NJ',
    status: 'Accepted',
    resubmissionCount: 0,
    lastUpdated: '2026-07-20T12:05:00Z',
  },
  {
    id: 'EVV-1002',
    visitId: 'VST-5433',
    patientName: 'Arthur Dent',
    caregiverName: 'Ford Prefect',
    date: '2026-07-20',
    beginTime: '09:00 AM',
    endTime: '01:00 PM',
    serviceType: 'S9122 - Home Health Aide',
    location: '42 Hitchhiker Way, Austin, TX',
    aggregator: 'HHAeXchange',
    state: 'TX',
    status: 'Rejected',
    rejectReason: 'Missing or Invalid Medicaid ID',
    resubmissionCount: 1,
    lastUpdated: '2026-07-21T08:15:00Z',
  },
  {
    id: 'EVV-1003',
    visitId: 'VST-5434',
    patientName: 'Martha Jones',
    caregiverName: 'Rose Tyler',
    date: '2026-07-21',
    beginTime: '07:30 AM',
    endTime: '11:30 AM',
    serviceType: 'T1019 - Personal Care',
    location: '99 Tardis Ln, Miami, FL',
    aggregator: 'Netsmart',
    state: 'FL',
    status: 'Rejected',
    rejectReason: 'Visit duration does not match authorized hours',
    resubmissionCount: 0,
    lastUpdated: '2026-07-21T11:45:00Z',
  },
  {
    id: 'EVV-1004',
    visitId: 'VST-5435',
    patientName: 'Bruce Wayne',
    caregiverName: 'Alfred Pennyworth',
    date: '2026-07-21',
    beginTime: '06:00 AM',
    endTime: '10:00 AM',
    serviceType: 'T1019 - Personal Care',
    location: '1007 Mountain Dr, Gotham, NJ',
    aggregator: 'HHAeXchange',
    state: 'NJ',
    status: 'Sent',
    resubmissionCount: 0,
    lastUpdated: '2026-07-21T10:10:00Z',
  },
  {
    id: 'EVV-1005',
    visitId: 'VST-5436',
    patientName: 'Diana Prince',
    caregiverName: 'Steve Trevor',
    date: '2026-07-19',
    beginTime: '02:00 PM',
    endTime: '06:00 PM',
    serviceType: 'S9122 - Home Health Aide',
    location: '1 Paradise Island, Tampa, FL',
    aggregator: 'Netsmart',
    state: 'FL',
    status: 'Accepted',
    resubmissionCount: 0,
    lastUpdated: '2026-07-19T18:05:00Z',
  },
];
